config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  as :user do
    get 'sign-up', to: 'devise/registrations#new', as: :sign_up
    get 'sign-in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    get 'profile', to: 'devise/registrations#edit', as: :profile
    put 'users/:user_id/admin', to: 'users/registrations#admin', as: :admin
    put 'users/:user_id/unadmin', to: 'users/registrations#unadmin', as: :unadmin
  end
  resources :companies do
    post '/join', to: 'companies#join', as: :join, on: :member
  end
  root 'pages#home'
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id          :integer          not null, primary key
#  name        :string
#  logo        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Company < ApplicationRecord
  has_many :users, dependent: :nullify
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :join]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      @company.reload
      current_user.update(company_id: @company.id, admin: true)
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  def join
    if current_user.update(company_id: @company.id)
      redirect_to root_url, notice: 'You joined '+@company.name
    else
      redirect_to companies_url, notice: 'You could not join this company'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def company_params
      params.require(:company).permit(:name, :logo, :description)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.haml
.list-group-item.list-group-item-success.d-flex.justify-content-between.align-items-center
    %p=company.name
    = link_to "Join",  join_company_path(company), method: 'post', class: "btn btn-light"

app/views/companies/_company_details.html.haml
.card.bg-danger.text-light.mt-4.mb-4
    = image_tag company.logo, class: "card-img-top", alt: "#{company.name} logo"
    .card-body
        %h3.card-title=company.name
        %p.card-text=company.description
    .card-footer
        - if current_user_is_company_admin?(company)
            = link_to 'Edit company', edit_company_path(company), class: "btn btn-light card-link"
            = link_to 'Delete company', company, method: 'delete', class: "btn btn-dark card-link", data: { confirm: 'Are you sure?' }

app/views/companies/_form.html.haml
.card.bg-primary.text-light.mt-4.mb-4
  .card-header
    %h1=title
  .card-body
    = form_for company do |f|
      = render 'layouts/model_errors', model: company

      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :logo
        = f.text_field :logo, class: "form-control"
      .form-group
        = f.label :description
        = f.text_area :description, class: "form-control"
      .form-group
        = f.submit 'Save', class: 'btn btn-light'

app/views/companies/edit.html.haml
.row
    .col-12.col-md-6.offset-md-3
        = render 'form', title: "Edit company", company: @company

app/views/companies/index.html.haml
%h1.text-center.mb-4.mt-4 Companies

.row 
  .col-12.col-md-6.offset-md-3
    - if @companies.blank?
      .alert.alert-primary No companies registered yet
    - else 
      .list-group 
        = render @companies 

app/views/companies/new.html.haml
.row
    .col-12.col-md-6.offset-md-3
        = render 'form', title: "New company", company: @company

app/views/companies/show.html.haml
.row 
  .col-12.col-md-4
    = render 'company_details', company: @company