config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }


  as :user do
    get 'sign-up', to: 'devise/registrations#new', as: :sign_up
    get 'sign-in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    get 'profile', to: 'devise/registrations#edit', as: :profile
    put 'users/:user_id/admin', to: 'users/registrations#admin', as: :admin
    put 'users/:user_id/unadmin', to: 'users/registrations#unadmin', as: :unadmin
  end
  resources :companies do
    post '/join', to: 'companies#join', as: :join, on: :member
  end
  root 'pages#home'
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %p{class: "alert  alert-dismissible fade show " + flash_class(key), role: "alert"}
    = value
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-primary
  = link_to 'Companies', root_path, class: 'navbar-brand'
  %button.navbar-toggler{type: "button", "data-toggle": "collapse", "data-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    - if current_user_without_company?
      %ul.navbar-nav
        - if user_signed_in?
          %li.navbar-item
            = link_to 'Join a company', companies_path, class: "nav-link #{active_class(companies_path)}"
          %li.navbar-item
            = link_to 'Create a company', new_company_path, class: "nav-link #{active_class(new_company_path)}"
  .navbar-nav
    - if user_signed_in?
      .dropdown
        %button#dropdownMenuButton.btn.btn-primary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          My account
        .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
          = link_to "Profile", profile_path, class: "dropdown-item"
          = link_to "Sign out", sign_out_path, method: "delete", class: "dropdown-item"
    - else
      = link_to 'Sign in', sign_in_path, class: 'nav-link'

app/views/layouts/_model_errors.html.haml
- if model.errors.any?
  .alert.alert-danger
    %ul
      - model.errors.full_messages.each do |message|
        %li=message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, user-scalable=no", :name => "viewport"}/
    %title Company manager
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container-fluid
      = yield